# Generated by Django 4.2.1 on 2023-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_category_name_clothingitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="clothing_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
