# Generated by Django 4.2.1 on 2023-05-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_clothes_clothing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
