# Generated by Django 4.2.1 on 2023-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_clothingitem_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clothingitem",
            old_name="product_id",
            new_name="clothes_id",
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="code",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
