# Generated by Django 4.2.1 on 2023-05-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_product_id_clothingitem_clothes_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clothingitem",
            old_name="clothes_id",
            new_name="clothes",
        ),
    ]
