# Generated by Django 4.2.1 on 2023-05-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_rename_clothes_id_clothingitem_clothes"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
