# Generated by Django 4.2.1 on 2023-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_inventory"),
        ("accounts", "0004_shoppingcart_remove_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="clothing_items",
            field=models.ManyToManyField(
                blank=True, null=True, to="products.clothingitem"
            ),
        ),
    ]
